[package]
name = "git-remote-gitarch"
version = "0.1.0"
edition = "2021"

[dependencies]
sp-keyring = "5.0.0"

[dependencies.subxt]
git = "https://github.com/paritytech/subxt"
branch = "master"

#[dependencies.tokio]
#version = "1.16.1"
#features = ["macros", "rt-multi-thread"]

[dependencies.codec]
package = "parity-scale-codec"
version = "2"
default-features = false
features = ["derive", "full", "bit-vec"]
